### ISSUE TITLE
Invoice payment updation not working

### ISSUE THREAD

**Issue by banna360** [Instamojo/instamojo-whmcs#2]
With test mode the payment is success. But the full amount is not credit back to invoice. There is some different in amount applying to invoice after the payment.

<img width="712" alt="screen shot 2016-11-04 at 5 30 58 pm" src="https://cloud.githubusercontent.com/assets/3896904/20004865/bf906eb6-a2b4-11e6-847e-bac5d9b0eb91.png">
<img width="1045" alt="screen shot 2016-11-04 at 5 33 17 pm" src="https://cloud.githubusercontent.com/assets/3896904/20004880/d510c150-a2b4-11e6-83c7-73b8c8fb3f37.png">

But in mail i can see payment 1329.79 recived. Also this reflected in IM Dashboard
<img width="639" alt="screen shot 2016-11-04 at 5 33 54 pm" src="https://cloud.githubusercontent.com/assets/3896904/20004890/e8bd6168-a2b4-11e6-9daf-e3de1c6a3f92.png">

<img width="715" alt="screen shot 2016-11-04 at 5 34 52 pm" src="https://cloud.githubusercontent.com/assets/3896904/20004906/05feb326-a2b5-11e6-9088-ab6ad7fc20c3.png">

Feel like some bug.

**Comment by banna360** [comment]
Did a lot of tested. Look like some issues with the conversion. Why this used? My log is here

**Edited Value##**

11/04/2016 06:01:37 pm | Amount converted from 29.49 to 1969.88 for currency code 'USD'.
11/04/2016 06:01:37 pm | Creating Instamojo order for 166
11/04/2016 06:01:37 pm | Instamojo Settings are Client id = XXXXXXXXX | client secret = XXXXXX } Testmode = 1
11/04/2016 06:01:37 pm | Data sending to instamojo for creating order Array
(
    [name] => Coregenie Technologies
    [email] => mail@XX.com
    [phone] => XXXXX
    [transaction_id] => 1478262697-166
    [amount] => 1969.88
    [currency] => INR
    [redirect_url] => http://XXXXXXXXX.com/modules/gateways/callback/instamojo.php
)

11/04/2016 06:01:38 pm | Response from server stdClass Object
(
    [order] => stdClass Object
        (
            [id] => bf23c089e1df48f2be882f17eb61eeef
            [transaction_id] => 1478262697-166
            [status] => pending
            [currency] => INR
            [amount] => 1969.88
            [name] => XXXXXXXXX Technologi
            [email] => mail@XXXXXXXXX.com
            [phone] => +XXXXXXXXX
            [description] => Instapay
            [redirect_url] => http://XXXXXXXXX.com/modules/gateways/callback/instamojo.php
            [webhook_url] => 
            [created_at] => 2016-11-04T12:31:38.029992Z
            [resource_uri] => https://test.instamojo.com/v2/gateway/orders/id:bf23c089e1df48f2be882f17eb61eeef/
        )
     [payment_options] => stdClass Object
       (
            [payment_url] => https://test.instamojo.com/@bannacoregenie/bf23c089e1df48f2be882f17eb61eeef?embed=form
        )

)

**Comment by ashwch** [comment]
The conversion is done because we only handle INR payments on Instamojo.

But the default currency defined on WHMCS or for a product might not be INR, in that case we try to convert it to INR before redirecting you to Instamojo and after the redirect we convert it back to the currency set for the user.

Could you please share following things:
- Your default currency
- Exchange rate set for INR
- Product's currency

Plus do check logs once again and let us know at which step you're seeing a conversion mismatch.

**Comment by banna360** [comment]
Its corrected by tweaking currency settings.

Thank You

**Comment by ashwch** [comment]
@banna360 Could you let us know which setting was incorrect. It would help us in rectifying problems faced by future users.

**Comment by banna360** [comment]
My default currency set as dollar. I renamed it to INR while i setup whmcs that cause issue here

Thanks and Regards,

HASANUL BANNA K

**Comment by aravindajith** [comment]
Hi Ashwini,

First of all, thanks a lot for creating the module. 

I have pretty much the same issue as reported by Mr. Banna. But changing the currency configuration would not be an ideal fix in my case. 

Let me explain it with an example transaction. 

- I have issued a sample invoice for INR 10 (for no existing products, just created a new invoice)
- I have logged in as customer and paid INR 10 using InstaMojo
- INR 10 has been debited from my account, and the same is credited to my Instamojo account
- But as per WHMCS invoice, I have only paid INR 0.15 and I have still INR 9.85 pending. (Screenshot - https://cl.ly/kg2u) 

My WHMCS setup

1. The default currency in WHMCS is USD and I want to keep it that way. Because I have more USD paying customers than INR
2. I have set pricing for USD and INR manually for each product so that it does not need to be converted when being redirected to and from InstaMojo
3. I will be creating invoices for the products/services that are not in the products list (like the example mentioned above) 

Could you please suggest a fix for the issue. 

Thank you

Aravind Ajith

Updated: PS: I am reporting this as a new issue.

**Comment by shwetarkumbhare** [comment]
Hi do let me know how did you fix that. Facing the same problem. Thanks in advance

**Comment by shwetarkumbhare** [comment]
> Hi Ashwini,
> 
> First of all, thanks a lot for creating the module.
> 
> I have pretty much the same issue as reported by Mr. Banna. But changing the currency configuration would not be an ideal fix in my case.
> 
> Let me explain it with an example transaction.
> 
> * I have issued a sample invoice for INR 10 (for no existing products, just created a new invoice)
> * I have logged in as customer and paid INR 10 using InstaMojo
> * INR 10 has been debited from my account, and the same is credited to my Instamojo account
> * But as per WHMCS invoice, I have only paid INR 0.15 and I have still INR 9.85 pending. (Screenshot - https://cl.ly/kg2u)
> 
> My WHMCS setup
> 
> 1. The default currency in WHMCS is USD and I want to keep it that way. Because I have more USD paying customers than INR
> 2. I have set pricing for USD and INR manually for each product so that it does not need to be converted when being redirected to and from InstaMojo
> 3. I will be creating invoices for the products/services that are not in the products list (like the example mentioned above)
> 
> Could you please suggest a fix for the issue.
> 
> Thank you
> 
> Aravind Ajith
> 
> Updated: PS: I am reporting this as a new issue.

Hi do let me know how did you fix that. Facing the same problem. Thanks in advance

**Comment by shwetarkumbhare** [comment]
> Its corrected by tweaking currency settings.
> 
> Thank You

Hi do let me know how did you fix that. Facing the same problem. Thanks in advance
